-- Grupos visibles de academia (decidido con el club, ago-2026).
--
-- Cambio de fondo: el grupo pasa a EXISTIR como entidad. Antes se decidió que no
-- —"mostrarlo confunde"— pero el club volvió con una definición precisa que sí se
-- puede modelar: **un grupo = academia + nivel + rango de edad**, y cada grupo
-- tiene VARIAS franjas horarias a las que sus niños pueden ir.
--
-- El rango de edad lo pone el club por grupo y PUEDE SOLAPARSE con otro. No se
-- usan bandas fijas: medido contra los 107 niños reales, cualquier banda global
-- parte por la mitad entre 16 y 33 de las 60 franjas que el club ya dicta (p. ej.
-- Jorge tiene martes 15:30 con niños de 9, 9 y 10 años). Imponer bandas obligaría
-- a partir grupos que en la cancha son uno solo.
--
-- Esta migración es ADITIVA: no borra ni cambia nada de lo que ya funciona. La
-- limpieza de lo viejo (inscripcion_horarios, niveles de bola, columnas muertas
-- de academias) va al final, cuando lo nuevo esté cargado y verificado.

-- ─────────────── Niveles ───────────────
-- Iniciación / Intermedio / Avanzado. Reemplazan a los de bola (roja, naranja,
-- verde, amarilla) y a principiantes/iniciados/intermedio, que se van en la
-- limpieza final.
create type public.academia_nivel as enum ('iniciacion', 'intermedio', 'avanzado');

/** Tope de niños por franja según el nivel. Iniciación 6 · Intermedio 5 · Avanzado 4. */
create or replace function public.cupo_nivel(p_nivel public.academia_nivel)
returns smallint
language sql
immutable
as $$
  select case p_nivel
    when 'iniciacion' then 6::smallint
    when 'intermedio' then 5::smallint
    when 'avanzado'   then 4::smallint
  end;
$$;

-- ─────────────── El grupo ───────────────
create table if not exists public.academia_grupo (
  id bigint generated by default as identity primary key,
  academia_id bigint not null references public.academias(id) on delete cascade,
  -- Editable: el club le cambia el nombre cuando quiera sin que nada más se mueva.
  nombre text not null,
  nivel public.academia_nivel not null,
  edad_min smallint not null,
  edad_max smallint not null,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint academia_grupo_edades check (edad_min >= 0 and edad_max >= edad_min),
  constraint academia_grupo_nombre_unico unique (academia_id, nombre)
);

comment on table public.academia_grupo is
  'Un grupo = academia + nivel + rango de edad. El nombre es libre y editable; los rangos pueden solaparse entre grupos.';
comment on column public.academia_grupo.nombre is
  'Editable por el club. Hoy: Disney en recreativa, tenistas en competencia.';

-- Regla del club: en COMPETENCIA solo existen intermedio y avanzado.
-- Va por trigger y no por CHECK porque la categoría vive en `academias`.
create or replace function public.grupo_nivel_valido()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare v_cat text;
begin
  select categoria into v_cat from public.academias where id = new.academia_id;
  if v_cat = 'competencia' and new.nivel = 'iniciacion' then
    raise exception 'En las academias de competencia no hay nivel de iniciación (solo intermedio y avanzado).'
      using errcode = 'check_violation';
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists grupo_nivel_valido_trg on public.academia_grupo;
create trigger grupo_nivel_valido_trg
  before insert or update of academia_id, nivel on public.academia_grupo
  for each row execute function public.grupo_nivel_valido();

-- ─────────────── Las franjas del grupo ───────────────
create table if not exists public.grupo_franja (
  id bigint generated by default as identity primary key,
  grupo_id bigint not null references public.academia_grupo(id) on delete cascade,
  dia_semana smallint not null check (dia_semana between 0 and 6),
  hora_inicio time not null,
  hora_fin time not null,
  profesor_id uuid references public.profiles(id) on delete set null,
  cancha text,
  -- null = se usa el tope del nivel (cupo_nivel). Se llena solo para excepciones.
  cupo smallint check (cupo is null or cupo > 0),
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  constraint grupo_franja_rango check (hora_fin > hora_inicio)
);

comment on table public.grupo_franja is
  'Cada horario habilitado de un grupo. El cupo NO bloquea: la app avisa cuando está por superarse o superado (decisión de Laura).';
comment on column public.grupo_franja.cupo is
  'Tope propio de esta franja. null = el del nivel (Iniciación 6 · Intermedio 5 · Avanzado 4).';

create unique index if not exists grupo_franja_uidx
  on public.grupo_franja (grupo_id, dia_semana, hora_inicio);

-- Para el pre-marcado del cierre y el cruce con las clases dictadas.
create index if not exists grupo_franja_dia_idx
  on public.grupo_franja (dia_semana, hora_inicio) where activo;

-- ─────────────── El niño, en un grupo y en sus franjas ───────────────
alter table public.inscripciones
  add column if not exists grupo_id bigint references public.academia_grupo(id) on delete set null;

comment on column public.inscripciones.grupo_id is
  'Grupo al que pertenece el niño. Nullable mientras convive con el modelo viejo; se vuelve obligatorio en la limpieza final.';

create table if not exists public.inscripcion_franja (
  id bigint generated by default as identity primary key,
  inscripcion_id bigint not null references public.inscripciones(id) on delete cascade,
  franja_id bigint not null references public.grupo_franja(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint inscripcion_franja_unica unique (inscripcion_id, franja_id)
);

comment on table public.inscripcion_franja is
  'A qué franjas de su grupo asiste el niño. Reemplaza a inscripcion_horarios: el horario ya no es del niño, es del grupo.';

create index if not exists inscripcion_franja_franja_idx
  on public.inscripcion_franja (franja_id);

-- ─────────────── RLS: los mismos roles que `inscripciones` ───────────────
alter table public.academia_grupo enable row level security;
alter table public.grupo_franja enable row level security;
alter table public.inscripcion_franja enable row level security;

create policy "academia_grupo_select" on public.academia_grupo for select to authenticated
  using (private.user_role() in ('superadmin','coord_admin','coord_deportivo','recepcion','profesor'));
create policy "academia_grupo_write" on public.academia_grupo for all to authenticated
  using (private.user_role() in ('superadmin','coord_admin','coord_deportivo'))
  with check (private.user_role() in ('superadmin','coord_admin','coord_deportivo'));

create policy "grupo_franja_select" on public.grupo_franja for select to authenticated
  using (private.user_role() in ('superadmin','coord_admin','coord_deportivo','recepcion','profesor'));
create policy "grupo_franja_write" on public.grupo_franja for all to authenticated
  using (private.user_role() in ('superadmin','coord_admin','coord_deportivo'))
  with check (private.user_role() in ('superadmin','coord_admin','coord_deportivo'));

-- Inscribir a un niño en una franja sí lo hace recepción, igual que `inscripciones`.
create policy "inscripcion_franja_select" on public.inscripcion_franja for select to authenticated
  using (private.user_role() in ('superadmin','coord_admin','coord_deportivo','recepcion','profesor'));
create policy "inscripcion_franja_write" on public.inscripcion_franja for all to authenticated
  using (private.user_role() in ('superadmin','coord_admin','coord_deportivo','recepcion'))
  with check (private.user_role() in ('superadmin','coord_admin','coord_deportivo','recepcion'));
