-- Horarios por inscrito: el corazón del modelo nuevo de academias.
--
-- El caso que el modelo viejo no podía representar (dicho por el coordinador el
-- 29-jul-2026): un grupo de niños va martes y jueves 4:30 con Jorge, y tres de
-- ellos además el sábado 12:00 con Graciano. Con el horario colgado de la
-- academia había que duplicar el grupo Y duplicar al niño. Ahora el horario
-- cuelga del INSCRITO: son tres filas de la misma inscripción.
--
-- El "grupo" no existe como entidad (decisión de Laura: mostrarlo confunde). Se
-- calcula agrupando por día + hora + profesor cuando se necesita: para pre-marcar
-- la asistencia y para el reporte de ocupación.

-- El nivel es del NIÑO, no de la academia (progresión de tenis: bola roja →
-- naranja → verde → amarilla).
alter table public.inscripciones
  add column if not exists nivel text;

comment on column public.inscripciones.nivel is
  'Nivel del niño (Bola Roja/Naranja/Verde/Amarilla, Principiantes…). Antes vivía en la academia.';
comment on column public.inscripciones.dias is
  'EN DESUSO: reemplazado por inscripcion_horarios, que además guarda hora, profesor y cancha.';
comment on column public.inscripciones.plan_frecuencia is
  'EN DESUSO: la frecuencia se deduce contando los horarios del inscrito.';

create table if not exists public.inscripcion_horarios (
  id bigint generated by default as identity primary key,
  inscripcion_id bigint not null references public.inscripciones(id) on delete cascade,
  dia_semana smallint not null check (dia_semana between 0 and 6),
  hora_inicio time not null,
  hora_fin time not null,
  profesor_id uuid references public.profiles(id) on delete set null,
  cancha text,
  created_at timestamptz not null default now(),
  constraint inscripcion_horarios_rango check (hora_fin > hora_inicio)
);

comment on table public.inscripcion_horarios is
  'Cuándo, con quién y dónde asiste cada inscrito. Un niño puede tener varias filas con profesores distintos.';

-- Un mismo inscrito no puede tener dos veces el mismo día a la misma hora.
create unique index if not exists inscripcion_horarios_uidx
  on public.inscripcion_horarios (inscripcion_id, dia_semana, hora_inicio);

-- Para el pre-marcado del cierre: "¿quién se esperaba el martes a las 16:00?"
create index if not exists inscripcion_horarios_dia_idx
  on public.inscripcion_horarios (dia_semana, hora_inicio);

-- ───────── Un niño, una academia por deporte ─────────
-- "No es normal que un niño esté en recreativa y de competencia al mismo tiempo,
-- no tiene sentido" (Laura). Sí puede hacer tenis y pádel. No se puede resolver
-- con un índice único porque el deporte vive en la academia, así que va por trigger.
create unique index if not exists inscripciones_miembro_academia_uidx
  on public.inscripciones (miembro_id, academia_id)
  where miembro_id is not null and activa;

create or replace function public.inscripcion_un_deporte()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_deporte public.deporte;
  v_otra text;
begin
  if new.miembro_id is null or not new.activa then
    return new;
  end if;

  select deporte into v_deporte from public.academias where id = new.academia_id;

  select a.nombre into v_otra
  from public.inscripciones i
  join public.academias a on a.id = i.academia_id
  where i.miembro_id = new.miembro_id
    and i.activa
    and a.deporte = v_deporte
    and i.academia_id <> new.academia_id
    and (tg_op = 'INSERT' or i.id <> new.id)
  limit 1;

  if v_otra is not null then
    raise exception 'Esta persona ya está inscrita en "%" (misma disciplina). Un niño va a una sola academia por deporte.', v_otra
      using errcode = 'check_violation';
  end if;

  return new;
end;
$$;

drop trigger if exists inscripcion_un_deporte_trg on public.inscripciones;
create trigger inscripcion_un_deporte_trg
  before insert or update of academia_id, miembro_id, activa on public.inscripciones
  for each row execute function public.inscripcion_un_deporte();

-- ───────── RLS: igual que inscripciones (mismo módulo, mismos roles) ─────────
alter table public.inscripcion_horarios enable row level security;

drop policy if exists inscripcion_horarios_select on public.inscripcion_horarios;
create policy inscripcion_horarios_select on public.inscripcion_horarios
  for select to authenticated using (true);

drop policy if exists inscripcion_horarios_write on public.inscripcion_horarios;
create policy inscripcion_horarios_write on public.inscripcion_horarios
  for all to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and p.role in ('superadmin', 'coord_admin', 'coord_deportivo', 'recepcion')
    )
  )
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and p.role in ('superadmin', 'coord_admin', 'coord_deportivo', 'recepcion')
    )
  );
